import { beforeEach, describe, expect, it } from 'vitest';
import { APP_COMMANDS } from '../src/commands/appCommands';
import { useUiStore } from '../src/stores/uiStore';
describe('workspace UI state', () => {
  beforeEach(() => useUiStore.setState({ outlineOpen: true, inspectorOpen: true, validationOpen: false, paletteOpen: false, shortcutsOpen: false, playgroundOpen: false, cardDensity: 'auto', canvasZoom: 1, edgeKind: 'affects', connectionSourceId: undefined, selectedRelationId: undefined, quickAdd: undefined, focusedGroupId: undefined }));
  it('keeps transient controls independent and cancellable', () => { const store = useUiStore.getState(); store.toggleOutline(); store.toggleValidation(); store.beginConnection('node-1'); store.setCardDensity('detailed'); expect(useUiStore.getState()).toMatchObject({ outlineOpen: false, validationOpen: true, connectionSourceId: 'node-1', cardDensity: 'detailed' }); store.cancelConnection(); expect(useUiStore.getState().connectionSourceId).toBeUndefined(); });
  it('defines unique centralized commands', () => { expect(new Set(APP_COMMANDS.map((command) => command.id)).size).toBe(APP_COMMANDS.length); expect(APP_COMMANDS.find((command) => command.id === 'save')?.shortcut).toBe('Ctrl+S'); });
  it('keeps relation selection independent from panel visibility', () => { useUiStore.getState().setSelectedRelation('edge-1'); useUiStore.getState().toggleOutline(); useUiStore.getState().toggleInspector(); expect(useUiStore.getState()).toMatchObject({ selectedRelationId: 'edge-1', outlineOpen: false, inspectorOpen: false }); });
  it('opens quick add with connection context and closes it without project state', () => { const store = useUiStore.getState(); store.openQuickAdd({ x: 80, y: 120 }, 'node-1', 'requires'); expect(useUiStore.getState().quickAdd).toEqual({ position: { x: 80, y: 120 }, sourceId: 'node-1', edgeKind: 'requires' }); store.closeQuickAdd(); expect(useUiStore.getState().quickAdd).toBeUndefined(); });
  it('tracks a focused group independently from the selected node', () => { useUiStore.getState().setFocusedGroup('group-1'); expect(useUiStore.getState()).toMatchObject({ focusedGroupId: 'group-1' }); useUiStore.getState().setFocusedGroup(); expect(useUiStore.getState().focusedGroupId).toBeUndefined(); });
  it('keeps the playground panel closed by default and toggles it independently', () => { expect(useUiStore.getState().playgroundOpen).toBe(false); useUiStore.getState().togglePlayground(); expect(useUiStore.getState()).toMatchObject({ playgroundOpen: true, outlineOpen: true, inspectorOpen: true }); });
  it('keeps the markdown preview and readiness view closed by default and toggles them independently', () => { expect(useUiStore.getState()).toMatchObject({ markdownPreviewOpen: false, readinessView: false }); useUiStore.getState().toggleMarkdownPreview(); useUiStore.getState().toggleReadinessView(); expect(useUiStore.getState()).toMatchObject({ markdownPreviewOpen: true, readinessView: true, outlineOpen: true }); });
});
