import { EDGE_LABELS, NODE_LABELS, type ProjectModel } from './types';

const safeName = (title: string) => title.trim().replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-|-$/g, '') || 'gdd-project';
const download = (content: BlobPart, type: string, name: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); };
export const projectMarkdown = (project: ProjectModel) => `# ${project.title}\n\n${project.pages.map((page) => { const nodes = project.objects.filter((node) => node.pageId === page.id); const edges = project.relations.filter((edge) => edge.pageId === page.id); return `## ${page.title}\n\n${nodes.map((node) => `### ${node.title}\n- Tür: ${NODE_LABELS[node.kind]}\n- Durum: ${node.status}\n${node.summary ? `- Özet: ${node.summary}\n` : ''}${node.checklist.length ? `- Kontrol listesi:\n${node.checklist.map((item) => `  - [${item.done ? 'x' : ' '}] ${item.text}`).join('\n')}\n` : ''}`).join('\n')}\n### Bağlantılar\n${edges.map((edge) => `- ${project.objects.find((node) => node.id === edge.source)?.title ?? edge.source} → ${project.objects.find((node) => node.id === edge.target)?.title ?? edge.target}: ${edge.customLabel || EDGE_LABELS[edge.kind]}`).join('\n') || '- Yok'}\n`; }).join('\n')}`;
export const projectSvg = (project: ProjectModel) => { const page = project.pages.find((item) => item.id === project.activePageId)!; const nodes = project.objects.filter((node) => node.pageId === page.id); const position = (id: string) => project.placements.find((item) => item.nodeId === id && item.pageId === page.id) ?? { x: 0, y: 0 }; const esc = (value: string) => value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[char]!)); const minX = Math.min(0, ...nodes.map((node) => position(node.id).x)) - 40; const minY = Math.min(0, ...nodes.map((node) => position(node.id).y)) - 40; const maxX = Math.max(800, ...nodes.map((node) => position(node.id).x + 210)) + 40; const maxY = Math.max(500, ...nodes.map((node) => position(node.id).y + 110)) + 40; return `<svg xmlns="http://www.w3.org/2000/svg" width="${maxX - minX}" height="${maxY - minY}" viewBox="${minX} ${minY} ${maxX - minX} ${maxY - minY}"><rect x="${minX}" y="${minY}" width="${maxX - minX}" height="${maxY - minY}" fill="#111827"/>${project.relations.filter((edge) => edge.pageId === page.id).map((edge) => { const source = position(edge.source); const target = position(edge.target); return `<path d="M ${source.x + 210} ${source.y + 55} L ${target.x} ${target.y + 55}" stroke="#9aa8c5" stroke-width="2" fill="none"/>`; }).join('')}${nodes.map((node) => { const point = position(node.id); return `<g><rect x="${point.x}" y="${point.y}" width="210" height="110" rx="10" fill="#20293a" stroke="#8b74ff"/><text x="${point.x + 14}" y="${point.y + 34}" fill="#fff" font-family="Arial" font-size="15">${esc(node.title)}</text><text x="${point.x + 14}" y="${point.y + 60}" fill="#b9c5df" font-family="Arial" font-size="11">${esc(NODE_LABELS[node.kind])}</text></g>`; }).join('')}</svg>`; };
export const downloadMarkdown = (project: ProjectModel) => download(projectMarkdown(project), 'text/markdown;charset=utf-8', `${safeName(project.title)}.md`);
export const downloadSvg = (project: ProjectModel) => download(projectSvg(project), 'image/svg+xml;charset=utf-8', `${safeName(project.title)}.svg`);
export const downloadPng = async (project: ProjectModel) => { const svg = projectSvg(project); const image = new Image(); const url = URL.createObjectURL(new Blob([svg], { type: 'image/svg+xml' })); image.src = url; await image.decode(); const canvas = document.createElement('canvas'); canvas.width = image.width; canvas.height = image.height; canvas.getContext('2d')?.drawImage(image, 0, 0); URL.revokeObjectURL(url); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/png')); if (blob) download(blob, 'image/png', `${safeName(project.title)}.png`); };
