import { emptyProject } from './project';
import type { GddEdge, GddGroup, GddNode, Placement, ProjectModel } from './types';

export type TemplateId = 'blank' | 'core-loop' | 'quest' | 'puzzle-level' | 'puzzle-tutorial';
export type ProjectTemplate = { id: TemplateId; name: string; description: string; category: string; useCase: string; startingCounts: string; preview: string; create: () => ProjectModel };
const node = (id: string, pageId: string, kind: GddNode['kind'], title: string, summary = ''): GddNode => ({ id, pageId, kind, title, summary, status: 'draft', tags: [], designIntent: '', playerExperience: '', specification: '', testNotes: '', properties: {}, checklist: [] });
const edge = (id: string, pageId: string, source: string, target: string, kind: GddEdge['kind']): GddEdge => ({ id, pageId, source, target, kind, customLabel: '' });
const placement = (nodeId: string, pageId: string, x: number, y: number): Placement => ({ nodeId, pageId, x, y });
type GroupDefinition = [id: string, title: string, color: string, members: string[]];
const template = (title: string, definitions: Array<[string, GddNode['kind'], string, string?, number?, number?]>, edges: Array<[string, string, string, GddEdge['kind']]>, groups: GroupDefinition[] = []): ProjectModel => {
  const project = emptyProject(); const pageId = project.activePageId;
  return { ...project, title, objects: definitions.map(([id, kind, name, summary]) => node(id, pageId, kind, name, summary)), placements: definitions.map(([id,,,, x = 0, y = 0]) => placement(id, pageId, x, y)), relations: edges.map(([id, source, target, kind]) => edge(id, pageId, source, target, kind)), groups: groups.map(([id, groupTitle, color, memberNodeIds]) => ({ id, pageId, title: groupTitle, color, memberNodeIds } satisfies GddGroup)) };
};

export const templates: ProjectTemplate[] = [
  { id: 'blank', name: 'Boş çalışma alanı', description: 'Fikirleri serbestçe yerleştirin.', category: 'Başlangıç', useCase: 'Sıfırdan özgür tasarım', startingCounts: '0 öğe', preview: 'Serbest tuval', create: emptyProject },
  { id: 'core-loop', name: 'Core loop', description: 'Oyuncu döngüsünü mekanik, ödül ve arayüz ile kurun.', category: 'Sistem', useCase: 'Temel oyun döngüsü', startingCounts: '4 öğe · 3 bağlantı', preview: 'Keşfet → Mücadele → Ödül', create: () => template('Core loop', [['explore','level','Keşfet','Oyuncu alanı inceler.',0,120], ['combat','mechanic','Mücadele','Temel karşılaşma döngüsü.',260,120], ['reward','entity','Ödül','Kaynak veya ilerleme ödülü.',520,120], ['hud','ui','Durum HUD','Kaynakları gösterir.',260,330]], [['e1','explore','combat','requires'], ['e2','combat','reward','produces'], ['e3','hud','combat','affects']]) },
  { id: 'quest', name: 'Quest flow', description: 'Görev adımlarını, arayüzü ve ödülü bağlayın.', category: 'İçerik', useCase: 'Görev akışı', startingCounts: '4 öğe · 3 bağlantı', preview: 'Al → Tamamla → Ödül', create: () => template('Quest flow', [['start','quest','Görevi al','',0,100], ['objective','quest','Hedefi tamamla','',260,100], ['reward','entity','Ödülü al','',520,100], ['journal','ui','Quest journal','',260,310]], [['q1','start','objective','requires'], ['q2','objective','reward','produces'], ['q3','journal','objective','affects']]) },
  { id: 'puzzle-level', name: 'Puzzle level design', description: 'Kural, state, keşif ve çözüm akışını birlikte kurun.', category: 'Puzzle', useCase: 'Tekil puzzle seviyesi', startingCounts: '9 öğe · 9 bağlantı · 3 grup', preview: 'Kural → State → Çözüm', create: () => template('Puzzle level design', [['verb','mechanic','Oyuncu fiili','Oyuncunun deneyebileceği temel hareket.',0,100], ['rule','mechanic','Temel kural','Puzzle mantığını açıklar.',260,100], ['constraint','mechanic','Kısıt','Kolay çözümleri sınırlar.',520,100], ['state','entity','Puzzle state','Dünyadaki güncel puzzle durumu.',260,290], ['hint','ui','İpucu','Oyuncuya okunabilir geri bildirim.',0,500], ['solution','quest','Çözüm adımı','Beklenen çözüm davranışı.',260,500], ['success','quest','Başarı koşulu','Puzzle tamamlanma kontrolü.',520,500], ['reset','mechanic','Başarısızlık / reset','Güvenli yeniden deneme kuralı.',520,290], ['reward','entity','Açılan içerik','Başarı sonrası ödül veya açılan yol.',780,500]], [['p1','verb','state','affects'], ['p2','rule','state','requires'], ['p3','constraint','solution','requires'], ['p4','state','hint','tested_by'], ['p5','hint','solution','affects'], ['p6','solution','success','requires'], ['p7','state','reset','affects'], ['p8','reset','state','affects'], ['p9','success','reward','produces']], [['rules','Girdi ve kurallar','#7058dd',['verb','rule','constraint']], ['state-group','State değişimleri','#19b8b2',['state','reset']], ['discovery','Oyuncu keşfi','#e59647',['hint','solution','success','reward']]]) },
  { id: 'puzzle-tutorial', name: 'Puzzle tutorial sequence', description: 'Kuralı öğretip kontrollü deneme ve bağımsız uygulamaya taşıyın.', category: 'Puzzle', useCase: 'Puzzle onboarding', startingCounts: '7 öğe · 7 bağlantı · 3 grup', preview: 'Göster → Dene → Ustalaş', create: () => template('Puzzle tutorial sequence', [['introduce','ui','Kuralı göster','Kuralın ilk, sade açıklaması.',0,100], ['guided','quest','Yönlendirilmiş deneme','Oyuncu ilk adımı güvenle uygular.',260,100], ['feedback','ui','Anlık geri bildirim','Doğru ve yanlış sonucu görünür kılar.',520,100], ['challenge','level','Serbest challenge','Kuralın bağımsız uygulaması.',780,100], ['state','entity','Tutorial state','Öğrenme ilerlemesini tutar.',260,320], ['reset','mechanic','Yumuşak reset','Hata sonrası anlaşılır geri dönüş.',520,320], ['mastery','quest','Ustalık kontrolü','Oyuncunun kuralı anladığını doğrular.',780,320]], [['t1','introduce','guided','requires'], ['t2','guided','feedback','tested_by'], ['t3','feedback','state','affects'], ['t4','state','challenge','requires'], ['t5','challenge','mastery','requires'], ['t6','feedback','reset','affects'], ['t7','reset','guided','affects']], [['teach','Öğret','#7058dd',['introduce','guided','feedback']], ['practice','Deneme state’i','#19b8b2',['state','reset']], ['mastery-group','Bağımsız uygulama','#e59647',['challenge','mastery']]]) },
];
export const findTemplate = (id: TemplateId) => templates.find((template) => template.id === id)!;
