import type { MouseEvent } from 'react';
import type { AppCommandId } from '../commands/appCommands';
import type { CardDensity } from '../stores/uiStore';

type Props = { title: string; dirty: boolean; filePath?: string; saveLabel: string; saveState: string; issueCount: number; canUndo: boolean; canRedo: boolean; density: CardDensity; run: (id: AppCommandId) => void; setDensity: (density: CardDensity) => void; onExportMarkdown: () => void; onExportSvg: () => void; onExportPng: () => void };

export function AppHeader({ title, dirty, filePath, saveLabel, saveState, issueCount, canUndo, canRedo, density, run, setDensity, onExportMarkdown, onExportSvg, onExportPng }: Props) {
  const runFromMenu = (event: MouseEvent<HTMLButtonElement>, id: AppCommandId) => {
    event.currentTarget.closest('details')?.removeAttribute('open');
    run(id);
  };

  return <header className="app-header"><div className="header-leading"><details className="menu"><summary aria-label="Dosya menüsü">Dosya</summary><div className="menu-popover"><button onClick={(event) => runFromMenu(event, 'new')}>Yeni <kbd>Ctrl+N</kbd></button><button onClick={(event) => runFromMenu(event, 'open')}>Aç <kbd>Ctrl+O</kbd></button><button onClick={(event) => runFromMenu(event, 'save')}>Kaydet <kbd>Ctrl+S</kbd></button><button onClick={(event) => runFromMenu(event, 'saveAs')}>Farklı kaydet <kbd>Ctrl+Shift+S</kbd></button><button onClick={onExportMarkdown}>Markdown indir</button><button onClick={onExportSvg}>SVG indir</button><button onClick={() => void onExportPng()}>PNG indir</button></div></details><div className="project-identity"><h1>{title}{dirty && <span className="dirty-dot" aria-label="Kaydedilmemiş değişiklikler">●</span>}</h1><span title={filePath}>{filePath ?? 'Yerel proje'}</span></div></div><nav aria-label="Proje komutları"><span className={`save-state ${saveState} ${dirty ? 'dirty' : ''}`}>{saveLabel}</span><button aria-label="Geri al" title="Geri al (Ctrl+Z)" disabled={!canUndo} onClick={() => run('undo')}>↶</button><button aria-label="Yinele" title="Yinele (Ctrl+Y)" disabled={!canRedo} onClick={() => run('redo')}>↷</button><button className={issueCount ? 'validation-error' : ''} onClick={() => run('validation')}>Kontrol <span className="badge">{issueCount}</span></button><button className="primary" onClick={() => run('save')}>Kaydet</button><details className="menu menu-right"><summary aria-label="Diğer komutlar">•••</summary><div className="menu-popover"><button onClick={(event) => runFromMenu(event, 'templates')}>Şablonlar</button><button onClick={(event) => runFromMenu(event, 'outline')}>Outline paneli</button><button onClick={(event) => runFromMenu(event, 'inspector')}>Inspector paneli</button><label>Kart ayrıntısı<select value={density} onChange={(event) => setDensity(event.target.value as CardDensity)}><option value="auto">Otomatik</option><option value="compact">Kompakt</option><option value="standard">Standart</option><option value="detailed">Detaylı</option></select></label><button onClick={(event) => runFromMenu(event, 'shortcuts')}>Klavye kısayolları</button></div></details></nav></header>;
}
