import type { MouseEvent } from 'react';
import type { AppCommandId } from '../commands/appCommands';
import { useT, useUiStore, type CardDensity } from '../stores/uiStore';

type Props = { title: string; dirty: boolean; filePath?: string; saveLabel: string; saveState: string; issueCount: number; canUndo: boolean; canRedo: boolean; density: CardDensity; run: (id: AppCommandId) => void; setDensity: (density: CardDensity) => void; onExportMarkdown: () => void; onExportSvg: () => void; onExportPng: () => void; onExportPdf: () => void };

export function AppHeader({ title, dirty, filePath, saveLabel, saveState, issueCount, canUndo, canRedo, density, run, setDensity, onExportMarkdown, onExportSvg, onExportPng, onExportPdf }: Props) {
  const t = useT();
  const language = useUiStore((state) => state.language);
  const setLanguage = useUiStore((state) => state.setLanguage);
  const runFromMenu = (event: MouseEvent<HTMLButtonElement>, id: AppCommandId) => { event.currentTarget.closest('details')?.removeAttribute('open'); run(id); };

  return <header className="app-header"><div className="header-leading"><details className="menu"><summary aria-label={t('header.fileMenuAria')}>{t('header.file')}</summary><div className="menu-popover"><button onClick={(event) => runFromMenu(event, 'new')}>{t('header.new')} <kbd>Ctrl+N</kbd></button><button onClick={(event) => runFromMenu(event, 'open')}>{t('header.open')} <kbd>Ctrl+O</kbd></button><button onClick={(event) => runFromMenu(event, 'save')}>{t('header.save')} <kbd>Ctrl+S</kbd></button><button onClick={(event) => runFromMenu(event, 'saveAs')}>{t('header.saveAs')} <kbd>Ctrl+Shift+S</kbd></button><button onClick={onExportMarkdown}>{t('header.exportMarkdown')}</button><button onClick={onExportSvg}>{t('header.exportSvg')}</button><button onClick={() => void onExportPng()}>{t('header.exportPng')}</button><button onClick={onExportPdf}>{t('header.exportPdf')}</button></div></details><div className="project-identity"><h1>{title}{dirty && <span className="dirty-dot" aria-label={t('header.unsavedIndicator')}>●</span>}</h1><span title={filePath}>{filePath ?? t('header.localProject')}</span></div></div><nav aria-label={t('header.projectCommandsAria')}><span className={`save-state ${saveState} ${dirty ? 'dirty' : ''}`}>{saveLabel}</span><button aria-label={t('header.undo')} title={t('header.undoTitle')} disabled={!canUndo} onClick={() => run('undo')}>↶</button><button aria-label={t('header.redo')} title={t('header.redoTitle')} disabled={!canRedo} onClick={() => run('redo')}>↷</button><button className={issueCount ? 'validation-error' : ''} onClick={() => run('validation')}>{t('header.check')} <span className="badge">{issueCount}</span></button><button className="primary" onClick={() => run('save')}>{t('header.save')}</button><details className="menu menu-right"><summary aria-label={t('header.more')}>•••</summary><div className="menu-popover"><button onClick={(event) => runFromMenu(event, 'templates')}>{t('header.templates')}</button><button onClick={(event) => runFromMenu(event, 'markdownPreview')}>{t('header.markdownPreview')}</button><label>{t('header.cardDensity')}<select value={density} onChange={(event) => setDensity(event.target.value as CardDensity)}><option value="auto">{t('header.densityAuto')}</option><option value="compact">{t('header.densityCompact')}</option><option value="standard">{t('header.densityStandard')}</option><option value="detailed">{t('header.densityDetailed')}</option></select></label><label>{t('app.language')}<select value={language} onChange={(event) => setLanguage(event.target.value as 'tr' | 'en')}><option value="tr">Türkçe</option><option value="en">English</option></select></label><button onClick={(event) => runFromMenu(event, 'shortcuts')}>{t('header.shortcuts')}</button></div></details></nav></header>;
}
