import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { applyNodeChanges, Background, Controls, MiniMap, ReactFlow, useNodesState, type Connection, type Edge, type Node, type OnConnect, type OnConnectEnd, type OnConnectStart, type OnNodeDrag, type OnNodesChange, type ReactFlowInstance } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { confirmRemoveNode, isEditingShortcutContext } from '../commands/nodeCommands';
import { confirmRemoveRelation } from '../commands/relationCommands';
import { groupFrameGeometry } from '../domain/groups';
import { validateProject } from '../domain/validation';
import { EDGE_LABELS, edgeKinds, type EdgeKind } from '../domain/types';
import { useProjectStore } from '../stores/projectStore';
import { useUiStore } from '../stores/uiStore';
import { GddEdge, type GddEdgeData } from './GddEdge';
import { GddGroupFrame, type GddGroupFrameData } from './GddGroupFrame';
import { GddNodeCard, type GddCardData } from './GddNodeCard';
import { GroupCreateDialog } from './GroupCreateDialog';
import { NodeQuickAdd } from './NodeQuickAdd';

const colors = { mechanic: '#8b74ff', entity: '#19b8b2', level: '#e59647', quest: '#e86e9b', ui: '#62a0ef', asset: '#83a963' };
const nodeTypes = { gdd: GddNodeCard, group: GddGroupFrame }; const edgeTypes = { gdd: GddEdge };
const ariaLabelConfig = { 'node.a11yDescription.default': 'Bir kart seçmek için Enter veya Boşluk tuşuna basın. Ok tuşlarıyla taşıyın.', 'edge.a11yDescription.default': 'Bir bağlantı seçmek için Enter veya Boşluk tuşuna basın.', 'controls.ariaLabel': 'Tuval kontrolleri', 'controls.zoomIn.ariaLabel': 'Yakınlaştır', 'controls.zoomOut.ariaLabel': 'Uzaklaştır', 'controls.fitView.ariaLabel': 'Tümünü görünür yap', 'controls.interactive.ariaLabel': 'Etkileşimi kilitle', 'minimap.ariaLabel': 'Tuval genel görünümü', 'handle.ariaLabel': 'Bağlantı noktası' };
type CanvasNodeData = GddCardData | GddGroupFrameData;
export const reconcileFlowNodes = (current: Node<CanvasNodeData>[], incoming: Node<CanvasNodeData>[], pointerDraggingId?: string) => { const currentById = new Map(current.map((node) => [node.id, node])); return incoming.map((next) => { const existing = currentById.get(next.id); if (!existing) return next; return { ...existing, ...next, position: next.id === pointerDraggingId ? existing.position : next.position }; }); };
const clientPosition = (event: MouseEvent | TouchEvent) => 'touches' in event ? event.changedTouches[0] : event;

export function Canvas() {
  const project = useProjectStore((state) => state.project); const selected = useProjectStore((state) => state.selectedNodeId); const select = useProjectStore((state) => state.select); const openDetail = useProjectStore((state) => state.openDetail); const moveNode = useProjectStore((state) => state.moveNode); const addRelation = useProjectStore((state) => state.addRelation); const addNode = useProjectStore((state) => state.addNode); const createGroup = useProjectStore((state) => state.createGroup);
  const edgeKind = useUiStore((state) => state.edgeKind); const setEdgeKind = useUiStore((state) => state.setEdgeKind); const sourceId = useUiStore((state) => state.connectionSourceId); const cancelConnection = useUiStore((state) => state.cancelConnection); const selectedRelationId = useUiStore((state) => state.selectedRelationId); const setSelectedRelation = useUiStore((state) => state.setSelectedRelation); const densitySetting = useUiStore((state) => state.cardDensity); const zoom = useUiStore((state) => state.canvasZoom); const setZoom = useUiStore((state) => state.setCanvasZoom); const openQuickAdd = useUiStore((state) => state.openQuickAdd);
  const [groupDialogOpen, setGroupDialogOpen] = useState(false); const density = densitySetting === 'auto' ? (zoom < .72 ? 'compact' : zoom > 1.22 ? 'detailed' : 'standard') : densitySetting; const pageId = project.activePageId;
  const issues = useMemo(() => validateProject(project), [project]); const invalidNodes = useMemo(() => new Set(issues.filter((issue) => issue.severity === 'error').map((issue) => issue.nodeId).filter(Boolean)), [issues]); const invalidEdges = useMemo(() => new Set(issues.filter((issue) => issue.severity === 'error').map((issue) => issue.relationId).filter(Boolean)), [issues]); const pageObjects = useMemo(() => project.objects.filter((object) => object.pageId === pageId), [project.objects, pageId]);
  const projectNodes = useMemo<Node<CanvasNodeData>[]>(() => { const frames = project.groups.filter((group) => group.pageId === pageId).flatMap((group) => { const frame = groupFrameGeometry(group, project.placements); return frame ? [{ id: `group-frame-${group.id}`, type: 'group', position: { x: frame.x, y: frame.y }, style: { width: frame.width, height: frame.height, zIndex: 0 }, data: { title: group.title, color: group.color }, draggable: false, selectable: false, connectable: false, focusable: false }] : []; }); const cards = pageObjects.map((item) => { const place = project.placements.find((entry) => entry.nodeId === item.id && entry.pageId === pageId) ?? { x: 0, y: 0 }; return { id: item.id, type: 'gdd', position: { x: place.x, y: place.y }, style: { zIndex: 1 }, selected: selected === item.id, data: { item, density, invalid: invalidNodes.has(item.id) }, ariaLabel: `${item.title} ${item.kind}` }; }); return [...frames, ...cards]; }, [project.groups, pageObjects, project.placements, pageId, selected, density, invalidNodes]);
  const [nodes, setNodes] = useNodesState<Node<CanvasNodeData>>(projectNodes); const pointerDraggingId = useRef<string | undefined>(undefined); const flowRef = useRef<ReactFlowInstance<Node<CanvasNodeData>, Edge<GddEdgeData>> | null>(null); const pointerRef = useRef<{ x: number; y: number } | undefined>(undefined);
  useEffect(() => setNodes((current) => reconcileFlowNodes(current, projectNodes, pointerDraggingId.current)), [projectNodes, setNodes]); useEffect(() => { pointerDraggingId.current = undefined; setSelectedRelation(); }, [pageId, setSelectedRelation]);
  const edges = useMemo<Edge<GddEdgeData>[]>(() => project.relations.filter((relation) => relation.pageId === pageId).map((relation) => ({ id: relation.id, type: 'gdd', source: relation.source, target: relation.target, selected: selectedRelationId === relation.id, animated: relation.kind === 'requires', ariaLabel: `${relation.customLabel || EDGE_LABELS[relation.kind]} bağlantısı`, data: { kind: relation.kind, label: EDGE_LABELS[relation.kind], customLabel: relation.customLabel, invalid: invalidEdges.has(relation.id) } })), [project.relations, pageId, invalidEdges, selectedRelationId]);
  const openQuickAddAt = useCallback((position: { x: number; y: number }, connectSourceId?: string) => { const flow = flowRef.current; if (flow) openQuickAdd(flow.screenToFlowPosition(position), connectSourceId, edgeKind); }, [edgeKind, openQuickAdd]);
  const onNodesChange: OnNodesChange<Node<CanvasNodeData>> = useCallback((changes) => { setNodes((current) => applyNodeChanges(changes, current)); changes.forEach((change) => { if (change.type === 'position' && change.position && change.dragging === false && pointerDraggingId.current !== change.id && !change.id.startsWith('group-frame-')) moveNode(change.id, change.position.x, change.position.y); }); }, [moveNode, setNodes]);
  const onNodeDragStart: OnNodeDrag<Node<CanvasNodeData>> = useCallback((_, node) => { pointerDraggingId.current = node.id; }, []); const onNodeDragStop: OnNodeDrag<Node<CanvasNodeData>> = useCallback((_, node) => { pointerDraggingId.current = undefined; if (!node.id.startsWith('group-frame-')) moveNode(node.id, node.position.x, node.position.y); }, [moveNode]); const onConnect: OnConnect = useCallback((connection: Connection) => { if (connection.source && connection.target) addRelation(connection.source, connection.target, edgeKind); }, [addRelation, edgeKind]);
  const onConnectStart: OnConnectStart = useCallback((_, params) => { pointerDraggingId.current = params.nodeId ?? undefined; }, []); const onConnectEnd: OnConnectEnd = useCallback((event, state) => { const source = state.fromNode?.id; if (source && !state.toNode && state.isValid !== true) { const point = clientPosition(event); openQuickAddAt({ x: point.clientX, y: point.clientY }, source); } pointerDraggingId.current = undefined; }, [openQuickAddAt]);
  useEffect(() => { const remove = (event: KeyboardEvent) => { if (!['Delete', 'Backspace'].includes(event.key) || isEditingShortcutContext(event.target)) return; if (selectedRelationId) { event.preventDefault(); void confirmRemoveRelation(selectedRelationId); } else if (selected) { event.preventDefault(); void confirmRemoveNode(selected); } }; window.addEventListener('keydown', remove); return () => window.removeEventListener('keydown', remove); }, [selected, selectedRelationId]);
  useEffect(() => { const quickAdd = (event: KeyboardEvent) => { if (event.key.toLowerCase() !== 'a' || !event.shiftKey || event.ctrlKey || event.metaKey || event.altKey || isEditingShortcutContext(event.target)) return; event.preventDefault(); openQuickAddAt(pointerRef.current ?? { x: window.innerWidth / 2, y: window.innerHeight / 2 }); }; window.addEventListener('keydown', quickAdd); return () => window.removeEventListener('keydown', quickAdd); }, [openQuickAddAt]);
  return <main className={`canvas density-${density}`}><div className="canvas-toolbar"><label>Bağlantı<select value={edgeKind} onChange={(event) => setEdgeKind(event.target.value as EdgeKind)}>{edgeKinds.map((kind) => <option key={kind} value={kind}>{EDGE_LABELS[kind]}</option>)}</select></label><button onClick={() => setGroupDialogOpen(true)}>Grup oluştur</button>{sourceId && <button onClick={cancelConnection}>Bağlamayı iptal et</button>}</div>{!pageObjects.length && <div className="canvas-empty"><h2>Bu sayfa henüz boş</h2><p>Bir GDD öğesi ekleyin veya hazır bir akış yerleştirin.</p><button onClick={() => addNode('mechanic')}>İlk öğeyi ekle</button></div>}<ReactFlow key={pageId} nodeTypes={nodeTypes} edgeTypes={edgeTypes} nodes={nodes} edges={edges} deleteKeyCode={null} onInit={(instance) => { flowRef.current = instance; }} onNodesChange={onNodesChange} onNodeDragStart={onNodeDragStart} onNodeDragStop={onNodeDragStop} onConnect={onConnect} onConnectStart={onConnectStart} onConnectEnd={onConnectEnd} onPaneContextMenu={(event) => { event.preventDefault(); openQuickAddAt({ x: event.clientX, y: event.clientY }); }} onMouseMove={(event) => { pointerRef.current = { x: event.clientX, y: event.clientY }; }} onNodeClick={(_, node) => { if (node.id.startsWith('group-frame-')) return; setSelectedRelation(); if (sourceId && sourceId !== node.id) { addRelation(sourceId, node.id, edgeKind); cancelConnection(); } select(node.id); }} onEdgeClick={(_, edge) => { select(); setSelectedRelation(edge.id); }} onNodeDoubleClick={(_, node) => { if (!node.id.startsWith('group-frame-')) openDetail(node.id); }} onPaneClick={() => { select(); setSelectedRelation(); cancelConnection(); }} onMoveEnd={(_, viewport) => setZoom(viewport.zoom)} ariaLabelConfig={ariaLabelConfig} fitView onlyRenderVisibleElements><Background gap={20} size={1} color="#303950" /><Controls /><MiniMap ariaLabel="Tuval genel görünümü" bgColor="#151b29" maskColor="rgba(5, 8, 16, .72)" nodeStrokeColor="#b9c5df" nodeStrokeWidth={2} nodeColor={(node) => colors[project.objects.find((object) => object.id === node.id)?.kind ?? 'mechanic']} pannable zoomable /></ReactFlow><NodeQuickAdd />{groupDialogOpen && <GroupCreateDialog nodes={pageObjects} onClose={() => setGroupDialogOpen(false)} onCreate={(title, color, members) => { createGroup(title, color, members); setGroupDialogOpen(false); }} />}</main>;
}
