import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { applyNodeChanges, Background, Controls, MiniMap, ReactFlow, useNodesState, type Connection, type Edge, type Node, type OnConnect, type OnConnectEnd, type OnConnectStart, type OnNodeDrag, type OnNodesChange, type ReactFlowInstance } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { confirmRemoveNode, isEditingShortcutContext } from '../commands/nodeCommands';
import { confirmRemoveRelation } from '../commands/relationCommands';
import { groupFrameGeometry } from '../domain/groups';
import { validateProject } from '../domain/validation';
import { EDGE_LABELS, edgeKinds, NODE_LABELS, nodeStatuses, STATUS_LABELS, type EdgeKind } from '../domain/types';
import { useProjectStore } from '../stores/projectStore';
import { useUiStore } from '../stores/uiStore';
import { GddEdge, type GddEdgeData } from './GddEdge';
import { GddGroupFrame, type GddGroupFrameData } from './GddGroupFrame';
import { GddNodeCard, type GddCardData } from './GddNodeCard';
import { GroupCreateDialog } from './GroupCreateDialog';
import { NodeQuickAdd } from './NodeQuickAdd';

const colors = { mechanic: '#8b74ff', entity: '#19b8b2', level: '#e59647', quest: '#e86e9b', ui: '#62a0ef', asset: '#83a963' };
const nodeTypes = { gdd: GddNodeCard, group: GddGroupFrame }; const edgeTypes = { gdd: GddEdge };
const ariaLabelConfig = { 'node.a11yDescription.default': 'Bir kart seçmek için Enter veya Boşluk tuşuna basın. Ok tuşlarıyla taşıyın.', 'edge.a11yDescription.default': 'Bir bağlantı seçmek için Enter veya Boşluk tuşuna basın.', 'controls.ariaLabel': 'Tuval kontrolleri', 'controls.zoomIn.ariaLabel': 'Yakınlaştır', 'controls.zoomOut.ariaLabel': 'Uzaklaştır', 'controls.fitView.ariaLabel': 'Tümünü görünür yap', 'controls.interactive.ariaLabel': 'Etkileşimi kilitle', 'minimap.ariaLabel': 'Tuval genel görünümü', 'handle.ariaLabel': 'Bağlantı noktası' };
type CanvasNodeData = GddCardData | GddGroupFrameData;
type FilterPopoverProps = { filter: import('../stores/uiStore').NodeFilter; tags: string[]; update: (patch: Partial<import('../stores/uiStore').NodeFilter>) => void };
function FilterPopover({ filter, tags, update }: FilterPopoverProps) {
  const toggle = <T,>(items: T[], value: T) => items.includes(value) ? items.filter((item) => item !== value) : [...items, value];
  return <div className="filter-popover" role="dialog" aria-label="Öğe filtreleri">
    <label>Arama<input autoFocus placeholder="Ara…" value={filter.query} onChange={(event) => update({ query: event.target.value })} /></label>
    <label><input type="checkbox" checked={filter.focusMode} onChange={(event) => update({ focusMode: event.target.checked })} />Odak modu</label>
    <fieldset><legend>Tür</legend>{(['mechanic','entity','level','quest','ui','asset'] as const).map((kind) => <button type="button" key={kind} aria-pressed={filter.kinds.includes(kind)} onClick={() => update({ kinds: toggle(filter.kinds, kind) })}>{NODE_LABELS[kind]}</button>)}</fieldset>
    <fieldset><legend>Durum</legend>{nodeStatuses.map((status) => <button type="button" key={status} aria-pressed={filter.statuses.includes(status)} onClick={() => update({ statuses: toggle(filter.statuses, status) })}>{STATUS_LABELS[status]}</button>)}</fieldset>
    {tags.length > 0 && <fieldset><legend>Etiket</legend>{tags.map((tag) => <button type="button" key={tag} aria-pressed={filter.tags.includes(tag)} onClick={() => update({ tags: toggle(filter.tags, tag) })}>{tag}</button>)}</fieldset>}
    <button type="button" onClick={() => update({ query: '', kinds: [], statuses: [], tags: [], focusMode: false })}>Filtreleri temizle</button>
  </div>;
}
export const nodeMatchesFilter = (node: import('../domain/types').GddNode, filter: import('../stores/uiStore').NodeFilter) => { const query = filter.query.trim().toLocaleLowerCase('tr'); const searchable = [node.title, node.summary, node.kind, node.status, ...node.tags, ...node.checklist.map((item) => item.text)].join(' ').toLocaleLowerCase('tr'); return (!query || searchable.includes(query)) && (!filter.kinds.length || filter.kinds.includes(node.kind)) && (!filter.statuses.length || filter.statuses.includes(node.status)) && (!filter.tags.length || filter.tags.every((tag) => node.tags.includes(tag))); };
export const reconcileFlowNodes = (current: Node<CanvasNodeData>[], incoming: Node<CanvasNodeData>[], pointerDraggingId?: string) => { const currentById = new Map(current.map((node) => [node.id, node])); return incoming.map((next) => { const existing = currentById.get(next.id); if (!existing) return next; return { ...existing, ...next, position: next.id === pointerDraggingId ? existing.position : next.position }; }); };
const clientPosition = (event: MouseEvent | TouchEvent) => 'touches' in event ? event.changedTouches[0] : event;

export function Canvas() {
  const project = useProjectStore((state) => state.project); const selected = useProjectStore((state) => state.selectedNodeId); const select = useProjectStore((state) => state.select); const openDetail = useProjectStore((state) => state.openDetail); const moveNode = useProjectStore((state) => state.moveNode); const addRelation = useProjectStore((state) => state.addRelation); const addNode = useProjectStore((state) => state.addNode); const createGroup = useProjectStore((state) => state.createGroup);
  const edgeKind = useUiStore((state) => state.edgeKind); const setEdgeKind = useUiStore((state) => state.setEdgeKind); const sourceId = useUiStore((state) => state.connectionSourceId); const cancelConnection = useUiStore((state) => state.cancelConnection); const selectedRelationId = useUiStore((state) => state.selectedRelationId); const setSelectedRelation = useUiStore((state) => state.setSelectedRelation); const densitySetting = useUiStore((state) => state.cardDensity); const zoom = useUiStore((state) => state.canvasZoom); const setZoom = useUiStore((state) => state.setCanvasZoom); const openQuickAdd = useUiStore((state) => state.openQuickAdd); const nodeFilter = useUiStore((state) => state.nodeFilter); const setNodeFilter = useUiStore((state) => state.setNodeFilter); const focusedGroupId = useUiStore((state) => state.focusedGroupId); const setFocusedGroup = useUiStore((state) => state.setFocusedGroup);
  const [groupDialogOpen, setGroupDialogOpen] = useState(false); const density = densitySetting === 'auto' ? (zoom < .72 ? 'compact' : zoom > 1.22 ? 'detailed' : 'standard') : densitySetting; const pageId = project.activePageId;
  const issues = useMemo(() => validateProject(project), [project]); const invalidNodes = useMemo(() => new Set(issues.filter((issue) => issue.severity === 'error').map((issue) => issue.nodeId).filter(Boolean)), [issues]); const invalidEdges = useMemo(() => new Set(issues.filter((issue) => issue.severity === 'error').map((issue) => issue.relationId).filter(Boolean)), [issues]); const pageObjects = useMemo(() => project.objects.filter((object) => object.pageId === pageId), [project.objects, pageId]);
  const matchingIds = useMemo(() => new Set(pageObjects.filter((item) => nodeMatchesFilter(item, nodeFilter)).map((item) => item.id)), [pageObjects, nodeFilter]); const contextIds = useMemo(() => { const ids = new Set(matchingIds); if (nodeFilter.focusMode) project.relations.filter((edge) => edge.pageId === pageId && (matchingIds.has(edge.source) || matchingIds.has(edge.target))).forEach((edge) => { ids.add(edge.source); ids.add(edge.target); }); return ids; }, [matchingIds, nodeFilter.focusMode, project.relations, pageId]); const activeGroup = useMemo(() => project.groups.find((group) => group.id === focusedGroupId && group.pageId === pageId), [project.groups, focusedGroupId, pageId]); const groupContextIds = useMemo(() => { const ids = new Set(activeGroup?.memberNodeIds ?? []); if (activeGroup) project.relations.filter((edge) => edge.pageId === pageId && (ids.has(edge.source) || ids.has(edge.target))).forEach((edge) => { ids.add(edge.source); ids.add(edge.target); }); return ids; }, [activeGroup, project.relations, pageId]); const hasGroupFocus = Boolean(activeGroup); const hasFilter = Boolean(nodeFilter.query || nodeFilter.kinds.length || nodeFilter.statuses.length || nodeFilter.tags.length); const availableTags = useMemo(() => [...new Set(pageObjects.flatMap((node) => node.tags))].sort(), [pageObjects]); const projectNodes = useMemo<Node<CanvasNodeData>[]>(() => { const frames = project.groups.filter((group) => group.pageId === pageId).flatMap((group) => { const frame = groupFrameGeometry(group, project.placements); return frame ? [{ id: `group-frame-${group.id}`, type: 'group', position: { x: frame.x, y: frame.y }, style: { width: frame.width, height: frame.height, zIndex: 0 }, data: { title: group.title, color: group.color, focused: group.id === focusedGroupId, onToggleFocus: () => setFocusedGroup(group.id === focusedGroupId ? undefined : group.id) }, draggable: false, selectable: false, connectable: false, focusable: false }] : []; }); const cards = pageObjects.map((item) => { const place = project.placements.find((entry) => entry.nodeId === item.id && entry.pageId === pageId) ?? { x: 0, y: 0 }; const filterVisible = nodeFilter.focusMode ? contextIds.has(item.id) : matchingIds.has(item.id); const groupVisible = !hasGroupFocus || groupContextIds.has(item.id); const dimmed = (hasFilter && !filterVisible) || (hasGroupFocus && !groupVisible); return { id: item.id, type: 'gdd', position: { x: place.x, y: place.y }, style: { zIndex: 1, opacity: dimmed ? (nodeFilter.focusMode || hasGroupFocus ? .08 : .2) : 1 }, selected: selected === item.id, data: { item, density, invalid: invalidNodes.has(item.id) }, ariaLabel: `${item.title} ${item.kind}` }; }); return [...frames, ...cards]; }, [project.groups, pageObjects, project.placements, pageId, selected, density, invalidNodes, matchingIds, contextIds, nodeFilter.focusMode, hasFilter, focusedGroupId, setFocusedGroup, hasGroupFocus, groupContextIds]);
  const [nodes, setNodes] = useNodesState<Node<CanvasNodeData>>(projectNodes); const pointerDraggingId = useRef<string | undefined>(undefined); const flowRef = useRef<ReactFlowInstance<Node<CanvasNodeData>, Edge<GddEdgeData>> | null>(null); const pointerRef = useRef<{ x: number; y: number } | undefined>(undefined);
  useEffect(() => setNodes((current) => reconcileFlowNodes(current, projectNodes, pointerDraggingId.current)), [projectNodes, setNodes]); useEffect(() => { pointerDraggingId.current = undefined; setSelectedRelation(); }, [pageId, setSelectedRelation]); useEffect(() => { if (focusedGroupId && !activeGroup) setFocusedGroup(); }, [focusedGroupId, activeGroup, setFocusedGroup]);
  const edges = useMemo<Edge<GddEdgeData>[]>(() => project.relations.filter((relation) => relation.pageId === pageId).map((relation) => { const filterDimmed = hasFilter && !(nodeFilter.focusMode ? contextIds.has(relation.source) && contextIds.has(relation.target) : matchingIds.has(relation.source) && matchingIds.has(relation.target)); const groupDimmed = hasGroupFocus && !(groupContextIds.has(relation.source) && groupContextIds.has(relation.target)); return { id: relation.id, type: 'gdd', source: relation.source, target: relation.target, selected: selectedRelationId === relation.id, animated: relation.kind === 'requires', className: filterDimmed || groupDimmed ? 'filter-dimmed-edge' : undefined, ariaLabel: `${relation.customLabel || EDGE_LABELS[relation.kind]} bağlantısı`, data: { kind: relation.kind, label: EDGE_LABELS[relation.kind], customLabel: relation.customLabel, invalid: invalidEdges.has(relation.id) } }; }), [project.relations, pageId, invalidEdges, selectedRelationId, hasFilter, nodeFilter.focusMode, contextIds, matchingIds, hasGroupFocus, groupContextIds]);
  const openQuickAddAt = useCallback((position: { x: number; y: number }, connectSourceId?: string) => { const flow = flowRef.current; if (flow) openQuickAdd(flow.screenToFlowPosition(position), connectSourceId, edgeKind); }, [edgeKind, openQuickAdd]);
  const onNodesChange: OnNodesChange<Node<CanvasNodeData>> = useCallback((changes) => { setNodes((current) => applyNodeChanges(changes, current)); changes.forEach((change) => { if (change.type === 'position' && change.position && change.dragging === false && pointerDraggingId.current !== change.id && !change.id.startsWith('group-frame-')) moveNode(change.id, change.position.x, change.position.y); }); }, [moveNode, setNodes]);
  const onNodeDragStart: OnNodeDrag<Node<CanvasNodeData>> = useCallback((_, node) => { pointerDraggingId.current = node.id; }, []); const onNodeDragStop: OnNodeDrag<Node<CanvasNodeData>> = useCallback((_, node) => { pointerDraggingId.current = undefined; if (!node.id.startsWith('group-frame-')) moveNode(node.id, node.position.x, node.position.y); }, [moveNode]); const onConnect: OnConnect = useCallback((connection: Connection) => { if (connection.source && connection.target) addRelation(connection.source, connection.target, edgeKind); }, [addRelation, edgeKind]);
  const onConnectStart: OnConnectStart = useCallback((_, params) => { pointerDraggingId.current = params.nodeId ?? undefined; }, []); const onConnectEnd: OnConnectEnd = useCallback((event, state) => { const source = state.fromNode?.id; if (source && !state.toNode && state.isValid !== true) { const point = clientPosition(event); openQuickAddAt({ x: point.clientX, y: point.clientY }, source); } pointerDraggingId.current = undefined; }, [openQuickAddAt]);
  useEffect(() => { const remove = (event: KeyboardEvent) => { if (!['Delete', 'Backspace'].includes(event.key) || isEditingShortcutContext(event.target)) return; if (selectedRelationId) { event.preventDefault(); void confirmRemoveRelation(selectedRelationId); } else if (selected) { event.preventDefault(); void confirmRemoveNode(selected); } }; window.addEventListener('keydown', remove); return () => window.removeEventListener('keydown', remove); }, [selected, selectedRelationId]);
  useEffect(() => { const quickAdd = (event: KeyboardEvent) => { if (event.key.toLowerCase() !== 'a' || !event.shiftKey || event.ctrlKey || event.metaKey || event.altKey || isEditingShortcutContext(event.target)) return; event.preventDefault(); openQuickAddAt(pointerRef.current ?? { x: window.innerWidth / 2, y: window.innerHeight / 2 }); }; window.addEventListener('keydown', quickAdd); return () => window.removeEventListener('keydown', quickAdd); }, [openQuickAddAt]);
  useEffect(() => { const filterShortcut = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'f') { event.preventDefault(); setNodeFilter({ filterOpen: true }); } }; window.addEventListener('keydown', filterShortcut); return () => window.removeEventListener('keydown', filterShortcut); }, [setNodeFilter]);
  useEffect(() => { const clearGroupFocus = (event: KeyboardEvent) => { if (event.key === 'Escape' && focusedGroupId && !isEditingShortcutContext(event.target)) { event.preventDefault(); setFocusedGroup(); } }; window.addEventListener('keydown', clearGroupFocus); return () => window.removeEventListener('keydown', clearGroupFocus); }, [focusedGroupId, setFocusedGroup]);
  useEffect(() => { if (nodeFilter.focusMode && contextIds.size) void flowRef.current?.fitView({ nodes: [...contextIds].map((id) => ({ id })), padding: .25, duration: 180 }); }, [nodeFilter.focusMode, contextIds]);
  useEffect(() => { if (hasGroupFocus && activeGroup?.memberNodeIds.length) void flowRef.current?.fitView({ nodes: activeGroup.memberNodeIds.map((id) => ({ id })), padding: .25, duration: 180 }); }, [hasGroupFocus, activeGroup]);
  return <main className={`canvas density-${density}`}><div className="canvas-toolbar"><label>Bağlantı<select value={edgeKind} onChange={(event) => setEdgeKind(event.target.value as EdgeKind)}>{edgeKinds.map((kind) => <option key={kind} value={kind}>{EDGE_LABELS[kind]}</option>)}</select></label><button onClick={() => setGroupDialogOpen(true)}>Grup oluştur</button><button aria-expanded={nodeFilter.filterOpen} onClick={() => setNodeFilter({ filterOpen: !nodeFilter.filterOpen })}>Filtre</button>{nodeFilter.filterOpen && <FilterPopover filter={nodeFilter} tags={availableTags} update={setNodeFilter} />}{sourceId && <button onClick={cancelConnection}>Bağlamayı iptal et</button>}</div>{!pageObjects.length && <div className="canvas-empty"><h2>Bu sayfa henüz boş</h2><p>Bir GDD öğesi ekleyin veya hazır bir akış yerleştirin.</p><button onClick={() => addNode('mechanic')}>İlk öğeyi ekle</button></div>}<ReactFlow key={pageId} nodeTypes={nodeTypes} edgeTypes={edgeTypes} nodes={nodes} edges={edges} deleteKeyCode={null} onInit={(instance) => { flowRef.current = instance; }} onNodesChange={onNodesChange} onNodeDragStart={onNodeDragStart} onNodeDragStop={onNodeDragStop} onConnect={onConnect} onConnectStart={onConnectStart} onConnectEnd={onConnectEnd} onPaneContextMenu={(event) => { event.preventDefault(); openQuickAddAt({ x: event.clientX, y: event.clientY }); }} onMouseMove={(event) => { pointerRef.current = { x: event.clientX, y: event.clientY }; }} onNodeClick={(_, node) => { if (node.id.startsWith('group-frame-')) return; setSelectedRelation(); if (sourceId && sourceId !== node.id) { addRelation(sourceId, node.id, edgeKind); cancelConnection(); } select(node.id); }} onEdgeClick={(_, edge) => { select(); setSelectedRelation(edge.id); }} onNodeDoubleClick={(_, node) => { if (!node.id.startsWith('group-frame-')) openDetail(node.id); }} onPaneClick={() => { select(); setSelectedRelation(); cancelConnection(); }} onMoveEnd={(_, viewport) => setZoom(viewport.zoom)} ariaLabelConfig={ariaLabelConfig} fitView onlyRenderVisibleElements><Background gap={20} size={1} color="#303950" /><Controls /><MiniMap ariaLabel="Tuval genel görünümü" bgColor="#151b29" maskColor="rgba(5, 8, 16, .72)" nodeStrokeColor="#b9c5df" nodeStrokeWidth={2} nodeColor={(node) => colors[project.objects.find((object) => object.id === node.id)?.kind ?? 'mechanic']} pannable zoomable /></ReactFlow><NodeQuickAdd />{groupDialogOpen && <GroupCreateDialog nodes={pageObjects} onClose={() => setGroupDialogOpen(false)} onCreate={(title, color, members) => { createGroup(title, color, members); setGroupDialogOpen(false); }} />}</main>;
}
