import { useCallback, useMemo } from 'react';
import { Background, Controls, MiniMap, ReactFlow, type Connection, type Edge, type Node, type NodeChange, type OnConnect } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { validateProject } from '../domain/validation';
import { EDGE_LABELS, edgeKinds, type EdgeKind } from '../domain/types';
import { useProjectStore } from '../stores/projectStore';
import { useUiStore } from '../stores/uiStore';
import { GddNodeCard, type GddCardData } from './GddNodeCard';

const colors = { mechanic: '#8b74ff', entity: '#19b8b2', level: '#e59647', quest: '#e86e9b', ui: '#62a0ef', asset: '#83a963' };
const nodeTypes = { gdd: GddNodeCard };
const ariaLabelConfig = { 'node.a11yDescription.default': 'Bir kart seçmek için Enter veya Boşluk tuşuna basın. Ok tuşlarıyla taşıyın.', 'edge.a11yDescription.default': 'Bir bağlantı seçmek için Enter veya Boşluk tuşuna basın.', 'controls.ariaLabel': 'Tuval kontrolleri', 'controls.zoomIn.ariaLabel': 'Yakınlaştır', 'controls.zoomOut.ariaLabel': 'Uzaklaştır', 'controls.fitView.ariaLabel': 'Tümünü görünür yap', 'controls.interactive.ariaLabel': 'Etkileşimi kilitle', 'minimap.ariaLabel': 'Tuval genel görünümü', 'handle.ariaLabel': 'Bağlantı noktası' };
export function Canvas() {
  const project = useProjectStore((state) => state.project); const selected = useProjectStore((state) => state.selectedNodeId);
  const select = useProjectStore((state) => state.select); const openDetail = useProjectStore((state) => state.openDetail); const moveNode = useProjectStore((state) => state.moveNode); const addRelation = useProjectStore((state) => state.addRelation); const addNode = useProjectStore((state) => state.addNode);
  const edgeKind = useUiStore((state) => state.edgeKind); const setEdgeKind = useUiStore((state) => state.setEdgeKind); const sourceId = useUiStore((state) => state.connectionSourceId); const cancelConnection = useUiStore((state) => state.cancelConnection); const densitySetting = useUiStore((state) => state.cardDensity); const zoom = useUiStore((state) => state.canvasZoom); const setZoom = useUiStore((state) => state.setCanvasZoom);
  const density = densitySetting === 'auto' ? (zoom < .72 ? 'compact' : zoom > 1.22 ? 'detailed' : 'standard') : densitySetting;
  const pageId = project.activePageId; const issues = useMemo(() => validateProject(project), [project]);
  const invalidNodes = new Set(issues.filter((issue) => issue.severity === 'error').map((issue) => issue.nodeId).filter(Boolean)); const invalidEdges = new Set(issues.filter((issue) => issue.severity === 'error').map((issue) => issue.relationId).filter(Boolean));
  const pageObjects = project.objects.filter((object) => object.pageId === pageId);
  const nodes = useMemo<Node<GddCardData>[]>(() => pageObjects.map((item) => { const place = project.placements.find((entry) => entry.nodeId === item.id && entry.pageId === pageId) ?? { x: 0, y: 0 }; return { id: item.id, type: 'gdd', position: { x: place.x, y: place.y }, selected: selected === item.id, data: { item, density, invalid: invalidNodes.has(item.id) }, ariaLabel: `${item.title} ${item.kind}` }; }), [pageObjects, project.placements, pageId, selected, density, invalidNodes]);
  const edges = useMemo<Edge[]>(() => project.relations.filter((relation) => relation.pageId === pageId).map((relation) => ({ id: relation.id, source: relation.source, target: relation.target, label: EDGE_LABELS[relation.kind], animated: relation.kind === 'requires', ariaLabel: `${EDGE_LABELS[relation.kind]} bağlantısı`, style: { stroke: invalidEdges.has(relation.id) ? '#ff667d' : '#7d89a3', strokeWidth: invalidEdges.has(relation.id) ? 3 : 1.5 }, labelStyle: { fill: '#d1daed', fontSize: 11 }, labelBgStyle: { fill: '#171c2b', stroke: '#46536e', strokeWidth: 1 }, labelBgPadding: [6, 4], labelBgBorderRadius: 4 })), [project.relations, pageId, invalidEdges]);
  const onNodesChange = useCallback((changes: NodeChange[]) => changes.forEach((change) => { if (change.type === 'position' && change.position && change.dragging === false) moveNode(change.id, change.position.x, change.position.y); }), [moveNode]);
  const onConnect: OnConnect = useCallback((connection: Connection) => { if (connection.source && connection.target) addRelation(connection.source, connection.target, edgeKind); }, [addRelation, edgeKind]);
  return <main className={`canvas density-${density}`}><div className="canvas-toolbar"><label>Bağlantı<select value={edgeKind} onChange={(event) => setEdgeKind(event.target.value as EdgeKind)}>{edgeKinds.map((kind) => <option key={kind} value={kind}>{EDGE_LABELS[kind]}</option>)}</select></label>{sourceId && <button onClick={cancelConnection}>Bağlamayı iptal et</button>}</div>{!pageObjects.length && <div className="canvas-empty"><h2>Bu sayfa henüz boş</h2><p>Bir GDD öğesi ekleyin veya hazır bir akış yerleştirin.</p><button onClick={() => addNode('mechanic')}>İlk öğeyi ekle</button></div>}<ReactFlow key={pageId} nodeTypes={nodeTypes} nodes={nodes} edges={edges} onNodesChange={onNodesChange} onConnect={onConnect} onNodeClick={(_, node) => { if (sourceId && sourceId !== node.id) { addRelation(sourceId, node.id, edgeKind); cancelConnection(); select(node.id); } else select(node.id); }} onNodeDoubleClick={(_, node) => openDetail(node.id)} onPaneClick={() => { select(); cancelConnection(); }} onMoveEnd={(_, viewport) => setZoom(viewport.zoom)} ariaLabelConfig={ariaLabelConfig} fitView onlyRenderVisibleElements><Background gap={20} size={1} color="#303950" /><Controls /><MiniMap ariaLabel="Tuval genel görünümü" bgColor="#151b29" maskColor="rgba(5, 8, 16, .72)" nodeStrokeColor="#b9c5df" nodeStrokeWidth={2} nodeColor={(node) => colors[project.objects.find((object) => object.id === node.id)?.kind ?? 'mechanic']} pannable zoomable /></ReactFlow></main>;
}
