import { useRef } from 'react';
import { MAX_SOURCE_FILE_BYTES, readImageAsDataUrl } from '../domain/image';
import { nodeLabel, type NodeKind } from '../domain/types';
import { feedback } from '../stores/feedbackStore';
import { useProjectStore } from '../stores/projectStore';
import { useT, useUiStore } from '../stores/uiStore';

const items: Array<{ kind: NodeKind; icon: string }> = [{ kind: 'mechanic', icon: 'M' }, { kind: 'entity', icon: 'E' }, { kind: 'level', icon: 'L' }, { kind: 'quest', icon: 'Q' }, { kind: 'ui', icon: 'UI' }, { kind: 'asset', icon: 'A' }, { kind: 'narrative', icon: 'N' }, { kind: 'system', icon: 'S' }, { kind: 'goal', icon: 'G' }, { kind: 'risk', icon: 'R' }];

export function CreationRail({ onTemplates, onAddIdea }: { onTemplates: () => void; onAddIdea: () => void }) {
  const t = useT(); const language = useUiStore((state) => state.language); const inputRef = useRef<HTMLInputElement>(null);
  const addNode = useProjectStore((state) => state.addNode); const addPlaygroundItem = useProjectStore((state) => state.addPlaygroundItem); const addPlaygroundImage = useProjectStore((state) => state.addPlaygroundImage);
  const setPlaygroundOpen = useUiStore((state) => state.setPlaygroundOpen); const outlineOpen = useUiStore((state) => state.outlineOpen); const inspectorOpen = useUiStore((state) => state.inspectorOpen); const toggleOutline = useUiStore((state) => state.toggleOutline); const toggleInspector = useUiStore((state) => state.toggleInspector);
  const addNote = () => { setPlaygroundOpen(true); addPlaygroundItem('note'); };
  const addImage = async (event: import('react').ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (file.size > MAX_SOURCE_FILE_BYTES) { feedback.toast(t('playground.imageTooLarge'), 'error'); return; } try { setPlaygroundOpen(true); addPlaygroundImage(await readImageAsDataUrl(file)); } catch (error) { feedback.toast(t('playground.imageReadFailed', { error: String(error) }), 'error'); } };
  return <aside className="creation-rail" aria-label={t('creationRail.aria')}><div className="rail-group" aria-label={t('creationRail.itemsGroup')}>{items.map(({ kind, icon }) => <button key={kind} title={t('creationRail.addKind', { kind: nodeLabel(kind, language) })} aria-label={t('creationRail.addKind', { kind: nodeLabel(kind, language) })} onClick={() => addNode(kind)}><span>{icon}</span></button>)}</div><span className="rail-divider" /><div className="rail-group" aria-label={t('creationRail.playgroundGroup')}><button title={t('creationRail.addNote')} aria-label={t('creationRail.addNote')} onClick={addNote}>N</button><button title={t('creationRail.addImage')} aria-label={t('creationRail.addImage')} onClick={() => inputRef.current?.click()}>IMG</button><input ref={inputRef} type="file" accept="image/*" hidden onChange={(event) => void addImage(event)} /></div><span className="rail-divider" /><button title={t('creationRail.addTemplate')} aria-label={t('creationRail.openTemplates')} onClick={onTemplates}>T</button><button title={t('creationRail.addIdeaTitle')} aria-label={t('creationRail.addIdea')} onClick={onAddIdea}>I</button><span className="rail-spacer" /><div className="rail-group" aria-label={t('creationRail.panelControls')}><button aria-label={t('creationRail.toggleOutline')} title={t('creationRail.toggleOutline')} aria-expanded={outlineOpen} aria-controls="outline-panel" onClick={toggleOutline}>O</button><button aria-label={t('creationRail.toggleInspector')} title={t('creationRail.toggleInspector')} aria-expanded={inspectorOpen} aria-controls="inspector-panel" onClick={toggleInspector}>I</button></div></aside>;
}
