import { confirmRemoveRelation } from '../commands/relationCommands';
import { edgeLabel, nodeLabel } from '../domain/types';
import { useProjectStore } from '../stores/projectStore';
import { useT, useUiStore } from '../stores/uiStore';
import { CommitFieldInput } from './CommitFieldInput';
import { CommitRelationLabelInput } from './CommitRelationLabelInput';
import { CommitTitleInput } from './CommitTitleInput';

export function Inspector() {
  const t = useT(); const language = useUiStore((state) => state.language);
  const project = useProjectStore((state) => state.project); const selectedId = useProjectStore((state) => state.selectedNodeId); const updateNode = useProjectStore((state) => state.updateNode); const updateRelation = useProjectStore((state) => state.updateRelation); const openDetail = useProjectStore((state) => state.openDetail); const addRelation = useProjectStore((state) => state.addRelation); const addGroupMembers = useProjectStore((state) => state.addGroupMembers); const removeGroupMembers = useProjectStore((state) => state.removeGroupMembers); const toggle = useUiStore((state) => state.toggleInspector);
  const selected = project.objects.find((object) => object.id === selectedId && object.pageId === project.activePageId);
  if (!selected) return <aside id="inspector-panel" className="inspector"><div className="panel-heading"><h2>{t('inspector.title')}</h2><button aria-label={t('inspector.close')} onClick={toggle}>›</button></div><p>{t('inspector.emptySelection')}</p></aside>;
  const pageObjects = project.objects.filter((object) => object.pageId === project.activePageId); const relations = project.relations.filter((edge) => edge.pageId === project.activePageId && (edge.source === selected.id || edge.target === selected.id)); const groups = project.groups.filter((group) => group.pageId === project.activePageId); const memberships = groups.filter((group) => group.memberNodeIds.includes(selected.id)); const availableGroups = groups.filter((group) => !group.memberNodeIds.includes(selected.id));
  return <aside id="inspector-panel" className="inspector"><div className="panel-heading"><h2>{nodeLabel(selected.kind, language)}</h2><button aria-label={t('inspector.close')} onClick={toggle}>›</button></div><button className="open-detail" onClick={() => openDetail(selected.id)}>{t('inspector.openFullDetail')}</button><label>{t('inspector.title.title')}<CommitTitleInput aria-label={t('inspector.titleAria')} value={selected.title} onCommit={(title) => updateNode(selected.id, { title })} /></label><label>{t('inspector.summary')}<CommitFieldInput multiline aria-label={t('inspector.summary')} value={selected.summary} onCommit={(summary) => updateNode(selected.id, { summary })} /></label><label>{t('inspector.connect')}<select defaultValue="" onChange={(event) => { const target = event.target.value; if (target) addRelation(selected.id, target, 'affects'); event.currentTarget.value = ''; }}><option value="">{t('inspector.pickItem')}</option>{pageObjects.filter((object) => object.id !== selected.id).map((object) => <option value={object.id} key={object.id}>{object.title}</option>)}</select></label><div className="relations"><strong>{t('inspector.relations')}</strong>{relations.map((edge) => <div className="relation-row" key={edge.id}><label>{t('inspector.customLabel')}<CommitRelationLabelInput aria-label={t('detail.customLabelAria', { label: edgeLabel(edge.kind, language) })} value={edge.customLabel} placeholder={edgeLabel(edge.kind, language)} onCommit={(customLabel) => updateRelation(edge.id, { customLabel })} /></label><button title={t('inspector.deleteRelation')} onClick={() => void confirmRemoveRelation(edge.id)}>{t('detail.deleteRelation')}</button></div>)}</div><div className="group-memberships"><strong>{t('inspector.groups')}</strong>{memberships.map((group) => <span key={group.id}><i style={{ background: group.color }} />{group.title || t('outline.unnamedGroup')}<button onClick={() => removeGroupMembers(group.id, [selected.id])}>{t('inspector.removeFromGroup')}</button></span>)}{availableGroups.length ? <label>{t('inspector.addToGroup')}<select defaultValue="" onChange={(event) => { if (event.target.value) addGroupMembers(event.target.value, [selected.id]); event.currentTarget.value = ''; }}><option value="">{t('inspector.pickGroup')}</option>{availableGroups.map((group) => <option key={group.id} value={group.id}>{group.title || t('outline.unnamedGroup')}</option>)}</select></label> : <small>{memberships.length ? t('inspector.noOtherGroups') : t('inspector.noGroupsYet')}</small>}</div></aside>;
}
