import { confirmRemoveRelation } from '../commands/relationCommands';
import { EDGE_LABELS, NODE_LABELS } from '../domain/types';
import { useProjectStore } from '../stores/projectStore';
import { useUiStore } from '../stores/uiStore';
import { CommitFieldInput } from './CommitFieldInput';
import { CommitRelationLabelInput } from './CommitRelationLabelInput';
import { CommitTitleInput } from './CommitTitleInput';

export function Inspector() {
  const project = useProjectStore((state) => state.project); const selectedId = useProjectStore((state) => state.selectedNodeId); const updateNode = useProjectStore((state) => state.updateNode); const updateRelation = useProjectStore((state) => state.updateRelation); const openDetail = useProjectStore((state) => state.openDetail); const addRelation = useProjectStore((state) => state.addRelation); const addGroupMembers = useProjectStore((state) => state.addGroupMembers); const removeGroupMembers = useProjectStore((state) => state.removeGroupMembers); const toggle = useUiStore((state) => state.toggleInspector);
  const selected = project.objects.find((object) => object.id === selectedId && object.pageId === project.activePageId);
  if (!selected) return <aside id="inspector-panel" className="inspector"><div className="panel-heading"><h2>Inspector</h2><button aria-label="Inspector panelini kapat" onClick={toggle}>›</button></div><p>Bu sayfada bir kart seçin.</p></aside>;
  const pageObjects = project.objects.filter((object) => object.pageId === project.activePageId); const relations = project.relations.filter((edge) => edge.pageId === project.activePageId && (edge.source === selected.id || edge.target === selected.id)); const groups = project.groups.filter((group) => group.pageId === project.activePageId); const memberships = groups.filter((group) => group.memberNodeIds.includes(selected.id)); const availableGroups = groups.filter((group) => !group.memberNodeIds.includes(selected.id));
  return <aside id="inspector-panel" className="inspector"><div className="panel-heading"><h2>{NODE_LABELS[selected.kind]}</h2><button aria-label="Inspector panelini kapat" onClick={toggle}>›</button></div><button className="open-detail" onClick={() => openDetail(selected.id)}>Tam detayı aç</button><label>Başlık<CommitTitleInput aria-label="Öğe başlığı" value={selected.title} onCommit={(title) => updateNode(selected.id, { title })} /></label><label>Özet<CommitFieldInput multiline aria-label="Özet" value={selected.summary} onCommit={(summary) => updateNode(selected.id, { summary })} /></label><label>Bağla<select defaultValue="" onChange={(event) => { const target = event.target.value; if (target) addRelation(selected.id, target, 'affects'); event.currentTarget.value = ''; }}><option value="">Öğe seçin…</option>{pageObjects.filter((object) => object.id !== selected.id).map((object) => <option value={object.id} key={object.id}>{object.title}</option>)}</select></label><div className="relations"><strong>İlişkiler</strong>{relations.map((edge) => <div className="relation-row" key={edge.id}><label>Özel yazı<CommitRelationLabelInput aria-label={`${EDGE_LABELS[edge.kind]} bağlantısı için özel yazı`} value={edge.customLabel} placeholder={EDGE_LABELS[edge.kind]} onCommit={(customLabel) => updateRelation(edge.id, { customLabel })} /></label><button title="Bağlantıyı sil" onClick={() => void confirmRemoveRelation(edge.id)}>Sil</button></div>)}</div><div className="group-memberships"><strong>Gruplar</strong>{memberships.map((group) => <span key={group.id}><i style={{ background: group.color }} />{group.title || 'İsimsiz grup'}<button onClick={() => removeGroupMembers(group.id, [selected.id])}>Çıkar</button></span>)}{availableGroups.length ? <label>Gruba ekle<select defaultValue="" onChange={(event) => { if (event.target.value) addGroupMembers(event.target.value, [selected.id]); event.currentTarget.value = ''; }}><option value="">Grup seçin…</option>{availableGroups.map((group) => <option key={group.id} value={group.id}>{group.title || 'İsimsiz grup'}</option>)}</select></label> : <small>{memberships.length ? 'Eklenebilecek başka grup yok.' : 'Bu sayfada henüz grup yok.'}</small>}</div></aside>;
}
